name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # Change if your main branch is different

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: . # Change if your public files are in a subfolder
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
